// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElPopover: typeof import('element-plus/es')['ElPopover']
}
export {}
