// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DocPopover: typeof import('./src/components/DocPopover.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    Map: typeof import('./src/components/map/Map.vue')['default']
    MapBar: typeof import('./src/components/map/MapBar.vue')['default']
    MapBeta: typeof import('./src/components/map/Map-beta.vue')['default']
    MapOpPopover: typeof import('./src/components/map/MapOpPopover.vue')['default']
    MapRender: typeof import('./src/components/map/MapRender.vue')['default']
    Note: typeof import('./src/components/note/Note.vue')['default']
    NotePopover: typeof import('./src/components/note/NotePopover.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
  }
}
