
version: '3'

services:
  zmind-frontend:
    container_name: zmind-frontend
    image: zanderzhao/zmind-frontend
    # image: zmind-frontend
    restart: always
    ports:
      - 3004:8080
    # network_mode: host
    # volumes:
    #   - ${PWD}/data:/app
    links:
      - zmind-backend
    environment:
      - NODE_ENV=production
      - WATER_PRINT_COPYRIGHT=ZMIND
      - ZMIND_FRONTEND_URL=http://127.0.0.1:3004
      - ZMIND_BACKEND_URL=http://127.0.0.1:3003
      - BAIDU_HM=https://hm.baidu.com/hm.js?zzz

  zmind-backend:
    container_name: zmind-backend
    image: zanderzhao/zmind-backend
    # image: zmind-backend
    ports:
      - 3003:3003  # 如果你的App需要公开端口，可以映射到宿主机
    links:
      - zmind-backend-redis
      - zmind-backend-mongodb
    environment:
      - NODE_ENV=production

  zmind-backend-redis:
    container_name: zmind-backend-redis
    image: redis:latest
    # 6379

  zmind-backend-mongodb:
    container_name: zmind-backend-mongodb
    image: mongo:latest
    # 27017
