
version: '3'

services:
  zmind-frontend:
    container_name: zmind-frontend
    image: zanderzhao/zmind-frontend
    # image: zmind-frontend
    restart: always
    ports:
      - 3004:8080
    # network_mode: host
    # volumes:
    #   - ${PWD}/data:/app
    environment:
      - NODE_ENV=production
      - WATER_PRINT_COPYRIGHT=ZMIND
      - ZMIND_FRONTEND_URL=http://127.0.0.1:3004
      - ZMIND_BACKEND_URL=http://127.0.0.1:3003
      - BAIDU_HM=https://hm.baidu.com/hm.js?zzz


